
services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - smsnet
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8087:80"
    volumes:
      - ./:/var/www/html
      - ./xconfig/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - smsnet
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sms
      MYSQL_USER: smsuser
      MYSQL_PASSWORD: usersms
      MYSQL_ROOT_PASSWORD: usersms
    ports:
      - "3307:3306"
    volumes:
      - smdbdata:/var/lib/mysql
    networks:
      - smsnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: usersms  # Use the same root password here as you set for the MySQL service
    ports:
      - "8088:80"  # This will expose phpMyAdmin on http://localhost:8080 on your host machine
    depends_on:
      - db  # This should be the name of your MySQL service
    networks:
      - smsnet 
  
  redis:
    image: redis:latest
    ports:
      - "6380:6380"
    networks:
      - smsnet 

networks:
  smsnet:

volumes:
  smdbdata:

